language: ruby

rvm:
  - 2.2.3
  - 2.3.0

env:
  - DB=sqlite

script:
  - export TZ=America/Mexico_City
  - date
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - cd spec/dummy
  - bundle exec rake hatchy:setup --trace
  - cd ../../
  - rspec spec/